
export const FETCH_CUSTOMERS  = 'FETCH_CUSTOMERS';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const INSERT_CUSTOMER = 'INSERT_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';

export const FETCH_MOVIES = 'FETCH_MOVIES';
export const UPDATE_MOVIE = 'UPDATE_CUSTOMER';
export const INSERT_MOVIE = 'INSERT_MOVIE';
export const DELETE_MOVIE= 'DELETE_MOVIE';